### ISSUE TITLE
Parallel Training running into problems

### ISSUE THREAD

**Issue by hamlinliu17** [vc1492a/tidd#84]
@vc1492a  I seem to be running into the parallel models problem, I am putting this issue here so we can try and resolve it when we have the chance.

**Comment by hamlinliu17** [comment]
@vc1492a  Finally solved the attribute issue. Just needed to `import fastai.distributed` in order to utilize the attributes. Going to adjust the code to allow for parallel training. Will work on a feature branch and push to it.

**Comment by vc1492a** [comment]
That's great to hear @hamlinliu17! Looking forward to reviewing the PR.

**Comment by hamlinliu17** [comment]
@vc1492a I think I got the parallel training works very well now. I just need to test and work out the out of sample stuff since my data directories are not configured correctly so that part is not running correctly at the moment.

**Comment by hamlinliu17** [comment]
Resolving bug in this [branch](https://github.com/vc1492a/tidd/tree/feature/parallel_training)

**Comment by hamlinliu17** [comment]
Currently, need to check if testing works. I ran into some errors with my data directory but it seems I need to rerun the training to rerun the out of sample? I re ran it but I will finish testing with the experiment this week

**Comment by hamlinliu17** [comment]
@vc1492a  I can run the code with parallel GPU included and it seems to work now. Going to create a PR for you to review
