### ISSUE TITLE
List of TIDs for future work

### ISSUE THREAD

**Issue by vc1492a** [vc1492a/tidd#90]
We need to put together a list of tsunami events which resulted in clear TID signatures. It would also be good if we could go ahead and get the data for those (in the same format as previous work) (12 days before the day of the earthquake, day of earthquake, and two days after if possible). 

Labels are important. We need estimated start times, but also end times specified for each location / event, for each satellite.

**Comment by vc1492a** [comment]
@MichelaRavanelli wanted to ask if you thought there was one more event we could identify and add to the list to gather data for (so we have an even 10). Any thoughts?

**Comment by vc1492a** [comment]
Related, made a visual to show the locations of the events. Useful for when we are explaining our work. 

![events](https://user-images.githubusercontent.com/2057896/122273255-148af780-ce96-11eb-96e8-83abb6c65afc.png)

**Comment by MichelaRavanelli** [comment]
> @MichelaRavanelli wanted to ask if you thought there was one more event we could identify and add to the list to gather data for (so we have an even 10). Any thoughts?

Hi Val, let me think about it, but I could definetely find another one!

**Comment by MichelaRavanelli** [comment]
> Related, made a visual to show the locations of the events. Useful for when we are explaining our work.
> 
> ![events](https://user-images.githubusercontent.com/2057896/122273255-148af780-ce96-11eb-96e8-83abb6c65afc.png)

Super cool!
It gives a perfect idea of the tsunamigenic potential of the Pacific zone!

**Comment by MichelaRavanelli** [comment]
I would plot also the Haida Gwaii event that is in Hawaii, so in the middle of Pacific! ;)

In any case, we could try if we see something with the 2013 Solomon Islands earthquake and tsunami.

**Comment by vc1492a** [comment]
Hey @MichelaRavanelli wanted to get an update on how Chile / Japan data prep is going, thanks!

**Comment by MichelaRavanelli** [comment]
Hi Val,
I finally finished processing the Chilean dataset that I sent you: it took me more time than I thought.

For what concerns Japan, I'm requesting the data since my access was expired.

Thanks for your patience!

**Comment by MichelaRavanelli** [comment]
An update about Japan data: they have just informed that the application can take up to 10 days.
I will keep you posted and thanks for your patience!

**Comment by vc1492a** [comment]
Thanks for the update @MichelaRavanelli!

**Comment by vc1492a** [comment]
> I would plot also the Haida Gwaii event that is in Hawaii, so in the middle of Pacific! ;)

Well, I would but this plot shows earthquake epicenters, _not_ locations where we see tsunami detections from TIDs.

**Comment by vc1492a** [comment]
![events](https://user-images.githubusercontent.com/2057896/123152050-00f10b00-d419-11eb-9ff0-150b7bbead12.png)

New plot!

**Comment by MichelaRavanelli** [comment]
Cool!

**Comment by vc1492a** [comment]
@MichelaRavanelli any updates you can share about Tohoku and the other events we have identified? We need the modeling data soon or we will miss or objectives for the project this fiscal year. Thanks!

**Comment by vc1492a** [comment]
@MichelaRavanelli any updates you can share about Tohoku and the other events we have identified? We need the modeling data soon or we will miss or objectives for the project this fiscal year. Thanks!
